name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt-hotspot
          cache: 'gradle'
      
      - name: Compile project
        run: ./gradlew build --no-daemon
